### ISSUE TITLE
Feature Request: Add beta for deploy run

### ISSUE THREAD

**Issue by muschellij2** [MarkEdmondson1234/googleCloudRunner#202]
Given https://github.com/rstudio/shiny/issues/2455#issuecomment-1295825518, if we put `"beta"` (or a flag) at https://github.com/MarkEdmondson1234/googleCloudRunner/blob/851775ce23b2fd1457ad4ed86aa60e9ace10835e/R/buildsteps_templates.R#L362, I think you can add `--session-affinity` in `gcloud_args`

**Comment by MarkEdmondson1234** [comment]
I'm a bit torn on this one as although it would enable features quicker but if we just wait those features will be in the production gcloud, and then we don't have an unstable API to maintain.  

In all cases one can copy the function over and add "beta" into a call for `cr_buildstep()` rather than relying on the derived functions, and I also sometimes use it to generate the YAML file and add it in there manually or via `cr_buildstep_edit`.
